//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOSSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level-headed
        ///Active
        ///Cowardly.
        /// </summary>
        internal static string AnimalPersonality {
            get {
                return ResourceManager.GetString("AnimalPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calf
        ///Young Cow
        ///Cow
        ///Mature Cow
        ///Calf
        ///Young Cow
        ///Cow
        ///Mature Cow
        ///Calf
        ///Young Cow
        ///Cow
        ///Mature Cow
        ///Cow
        ///Mature Cow
        ///Jersey Calf
        ///Young Jersey Cow
        ///Jersey Cow
        ///Mature Jersey Cow
        ///Jersey Calf
        ///Young Jersey Cow
        ///Jersey Cow
        ///Mature Jersey Cow
        ///Lamb
        ///Young Sheep
        ///Sheep
        ///Mature Sheep
        ///Suffolk Lamb
        ///Young Suffolk Sheep
        ///Suffolk Sheep
        ///Mature Suffolk Sheep
        ///Chick
        ///Young Chicken
        ///Chicken
        ///Mature Chicken
        ///Silkie Chick
        ///Young Silkie Chicken
        ///Silkie Chicken
        ///Mature Silkie Chicken
        ///Araucana Chick
        ///Young Araucana Chk. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalType {
            get {
                return ResourceManager.GetString("AnimalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Fence
        ///Wooden Gate
        ///Wooden Door
        ///Stone Fence
        ///Stone Gate
        ///Stone Door
        ///Bamboo Fence
        ///Bamboo Gate
        ///Bamboo Door
        ///Red Fence
        ///Red Gate
        ///Red Door
        ///Green Fence
        ///Green Gate
        ///Green Door
        ///Blue Fence
        ///Blue Gate
        ///Blue Door
        ///Yellow Fence
        ///Yellow Gate
        ///Yellow Door
        ///Pink Fence
        ///Pink Gate
        ///Pink Door
        ///Purple Fence
        ///Purple Gate
        ///Purple Door
        ///White Fence
        ///White Gate
        ///White Door
        ///Black Fence
        ///Black Gate
        ///Black Door
        ///Silver Fence
        ///Silver Gate
        ///Silver Door
        ///Golden Fence
        ///Golden Gate
        ///Golden Door
        ///Bovine Fence
        ///Bovine Gate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlueprintName {
            get {
                return ResourceManager.GetString("BlueprintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Fence Set
        ///Stone Fence Set
        ///Bamboo Fence Set
        ///Red Fence Set
        ///Green Fence Set
        ///Blue Fence Set
        ///Yellow Fence Set
        ///Pink Fence Set
        ///Purple Fence Set
        ///White Fence Set
        ///Black Fence Set
        ///Silver Fence Set
        ///Golden Fence Set
        ///Bovine Fence Set
        ///Fluffy Fence Set
        ///Guardrail Set
        ///Eastern Wall Set
        ///Stone Wall Set
        ///Brick Wall Set
        ///Brick Road Set
        ///Black Brick Road Set
        ///Red Brick Road Set
        ///Stone Road Set
        ///Blue Stone Road Set
        ///Green Stone Road Set
        ///P. Wooden Road Set
        ///Y. Wooden Road Set
        ///Wooden Road Set
        ///Bl. Checked Ro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlueprintSetName {
            get {
                return ResourceManager.GetString("BlueprintSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///19
        ///20
        ///21
        ///22
        ///23
        ///24
        ///25
        ///26
        ///27
        ///28
        ///29
        ///30
        ///31
        ///32
        ///33
        ///34
        ///35
        ///36
        ///37
        ///38
        ///39
        ///40
        ///41
        ///42
        ///43
        ///44
        ///45
        ///46
        ///47
        ///48
        ///49
        ///50
        ///51
        ///52
        ///53
        ///54
        ///55
        ///56
        ///57
        ///58
        ///59
        ///60
        ///61
        ///62
        ///63
        ///64
        ///65
        ///66
        ///67
        ///68
        ///69
        ///70
        ///71
        ///72
        ///73
        ///74
        ///75
        ///76
        ///77
        ///78
        ///79
        ///80
        ///81
        ///82
        ///83
        ///84
        ///85
        ///86
        ///87
        ///88
        ///89
        ///90
        ///91
        ///92
        ///93
        ///94
        ///95
        ///96
        ///97
        ///98
        ///99
        ///100
        ///101
        ///102
        ///OFFERING_COUNT
        ///104
        ///105
        ///106
        ///107
        ///108
        ///109
        ///110
        ///111
        ///112
        ///113
        ///114
        ///115
        ///116
        ///117
        ///118
        ///119
        ///120
        ///121
        ///122        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventFlag {
            get {
                return ResourceManager.GetString("EventFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Hoe
        ///Hoe
        ///Copper Hoe
        ///Silver Hoe
        ///Golden Hoe
        ///Master Hoe
        ///Orichalcum Hoe
        ///Philosopher&apos;s Hoe
        ///Old Watering Can
        ///Watering Can
        ///Copper Watering Can
        ///Silver Watering Can
        ///Golden Watering Can
        ///Master Watering Can
        ///Orichalcum Watering Can
        ///Philos. Watering Can
        ///Old Sickle
        ///Sickle
        ///Golden Sickle
        ///Master Sickle
        ///Philosopher&apos;s Sickle
        ///Old Axe
        ///Axe
        ///Golden Axe
        ///Master Axe
        ///Philosopher&apos;s Axe
        ///Old Hammer
        ///Hammer
        ///Golden Hammer
        ///Master Hammer
        ///Philosopher&apos;s Hammer
        ///Old Milker
        ///Milker
        ///Golden Milker
        ///Master Milker
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools
        ///Seeds
        ///Vesture
        ///Cooking
        ///Wardrobe
        ///Products
        ///Fishes
        ///Insects
        ///Others
        ///Fence
        ///Decorations
        ///Gardening
        ///Paths
        ///House
        ///Wallpaper / Floors
        ///Facilities
        ///Unknown.
        /// </summary>
        internal static string ItemObjectCategory {
            get {
                return ResourceManager.GetString("ItemObjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spr
        ///Sum
        ///Fal
        ///Win.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fritz
        ///Klaus
        ///Raeger
        ///Mistel
        ///Nadi
        ///Kamil
        ///Elise
        ///Iris
        ///Lillie
        ///Agate
        ///Angela
        ///Licorice
        ///Eda
        ///Giorgio
        ///Veronica
        ///Maurice
        ///Melanie
        ///Marian
        ///Otmar
        ///Jonas
        ///Margot
        ///Lutz
        ///Gunther
        ///Corona
        ///Son
        ///Daughter
        ///Witchie
        ///Dessie
        ///Flik
        ///Mora
        ///Pepita
        ///Gusto
        ///Torque.
        /// </summary>
        internal static string NPCName {
            get {
                return ResourceManager.GetString("NPCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Fence
        ///Wooden Gate
        ///Wooden Door
        ///Stone Fence
        ///Stone Gate
        ///Stone Door
        ///Bamboo Fence
        ///Bamboo Gate
        ///Bamboo Door
        ///Red Fence
        ///Red Gate
        ///Red Door
        ///Green Fence
        ///Green Gate
        ///Green Door
        ///Blue Fence
        ///Blue Gate
        ///Blue Door
        ///Yellow Fence
        ///Yellow Gate
        ///Yellow Door
        ///Pink Fence
        ///Pink Gate
        ///Pink Door
        ///Purple Fence
        ///Purple Gate
        ///Purple Door
        ///White Fence
        ///White Gate
        ///White Door
        ///Black Fence
        ///Black Gate
        ///Black Door
        ///Silver Fence
        ///Silver Gate
        ///Silver Door
        ///Golden Fence
        ///Golden Gate
        ///Golden Door
        ///Bovine Fence
        ///Bovine Gate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Boys&apos; Duds
        ///Farm Girls&apos; Duds
        ///Boys&apos; Overalls
        ///Girls&apos; Overalls
        ///Purple-Checked Jacket
        ///Work Apron
        ///Navy Streetwear
        ///Vintage V-Neck Dress
        ///Blue Work Clothes
        ///Orange Work Shorts
        ///Green Hoodie
        ///Apron Skirt
        ///Boys&apos; Jumpsuit
        ///Girls&apos; Jumpsuit
        ///Knickerbockers
        ///Smith&apos;s Outfit
        ///Red Farm Boys&apos; Duds
        ///Purple Farm Girls&apos; Duds
        ///Black Boys&apos; Overalls
        ///Peach Girls&apos; Overalls
        ///Green-Checked Jacket
        ///Gardening Outfit
        ///White Streetwear
        ///Aqua Blue V-Neck Dress
        ///Orange Work Outfit
        ///Blue Work Shorts
        ///Red Hoodie
        ///Green &amp; Cream Ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatternName {
            get {
                return ResourceManager.GetString("PatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open 1
        ///Open 2
        ///Open 3
        ///Open 4
        ///Open 5
        ///Open 6
        ///Open 7
        ///Open 8
        ///Open 9
        ///Open 10
        ///Open 11
        ///Open 12
        ///Open 13
        ///Open 14
        ///Open 15
        ///Open 16
        ///Open 17
        ///Open 18
        ///Open 19
        ///Open 20
        ///Open 21
        ///Open 22
        ///Open 23
        ///Open 24
        ///Open 25
        ///Open 26
        ///Open 27
        ///Open 28
        ///Navy Streetwear
        ///Vintage V-Neck Dress
        ///Smith&apos;s Outfit
        ///Black Smith&apos;s Outfit
        ///Boys&apos; Climber Outfit
        ///Girls&apos; Climber Outfit
        ///Dashing Prince Uniform
        ///Stylish Blue Jacket
        ///White Habit
        ///Magical Girl Costume
        ///Witchy Wear
        ///Cat Costume
        ///Dog Costume
        ///Bear Costume
        ///Panda Costume        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatternSetName {
            get {
                return ResourceManager.GetString("PatternSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salad Recipes
        ///Basic Soup Recipes
        ///Basic Grilling Recipes
        ///Basic Meal-Pot Recipes
        ///Basic Rice Recipes
        ///Basic Starch Recipes
        ///Basic Dessert Recipes
        ///Basic Drink Recipes
        ///Cooking Recipe Set 1
        ///Cooking Recipe Set 2
        ///Cooking Recipe Set 3
        ///Cooking Recipe Set 4
        ///Cooking Recipe Set 5
        ///Cooking Recipe Set 6
        ///Cooking Recipe Set 7
        ///Cooking Recipe Set 8
        ///Cooking Recipe Set 9
        ///Cooking Recipe Set 10
        ///Cooking Recipe Set 11
        ///Cooking Recipe Set 12
        ///Cooking Recipe Set 13
        ///Cooking Recipe Set 14
        ///Cooking Recipe Set 15
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecipeSetName {
            get {
                return ResourceManager.GetString("RecipeSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Store
        ///Carpenter Shop
        ///Anique Shop
        ///Silk Country
        ///Cabin Country
        ///Sakura Country
        ///Wheat Country
        ///Rose Country
        ///Tropical Country
        ///Ice Country.
        /// </summary>
        internal static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Crops
        ///Summer Crops
        ///Fall Crops
        ///Winter Crops
        ///Flowers
        ///Tea Leaves
        ///Spices
        ///Grains
        ///Mountain Crops
        ///Wardrobe
        ///Tools
        ///Fish
        ///Materials
        ///Cooking
        ///Products
        ///Eggs/Diary
        ///Wine
        ///Wallpaper/Floors
        ///Objects
        ///Furniture
        ///Other.
        /// </summary>
        internal static string TradingCategory {
            get {
                return ResourceManager.GetString("TradingCategory", resourceCulture);
            }
        }
    }
}
